# Generated by Django 3.2.12 on 2022-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('init_date', models.DateField()),
                ('finish_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
                ('logo', models.FilePathField(path='/img')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(null=True, path='/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='projects.Technology'),
        ),
    ]
